name: To Azure
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v3  

      - name: Check ls
        run: ls

      - name: Update application configuration
        run: |
          sed -i 's/server.address=.*/server.address=0.0.0.0/' application.properties
          sed -i 's/server.port=.*/server.port=80/' application.properties

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221535:${{ github.sha }}
      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221535:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-20221535
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221535:${{ github.sha }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: 20221535
          location: 'france central'
          ports: 80
          
      # - name: ping
      #   run: ping devops-20221535.francecentral.azurecontainer.io

      # - name: verbose
      #   run: curl -v "http://devops-20221535.francecentral.azurecontainer.io/?lat=5.902785&lon=102.754175"

      # - name: appel api
      #   run: curl "http://devops-20221535.francecentral.azurecontainer.io/?lat=5.902785&lon=102.754175"

      - name: 'Check job'
        run: echo " This job's status is ${{ job.status }} !"
