name: "ACR & ACI Deployment"
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Display Azure Login Result
        run: echo "Azure Login Successful"

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Display ACR Login Result
        run: echo "Azure Container Registry Login Successful"

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221535
          echo "Docker image built successfully"

      - name: Push Docker image to Azure Container Registry
        run: |
          echo "Pushing Docker image to Azure Container Registry..."
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221535
          echo "Docker image pushed successfully"

      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          location: france central
          dns-name-label: devops-20221535
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20221535
          name: 20221535
